### ISSUE TITLE
Audio Player autostart doesnt work

### ISSUE THREAD

**Issue by warrengay** [hunter-koppen/PlayAudio#2]
I've upgraded the widget to Mx 10 and when using the Audio Player the audio starts automatically whether the 'Autostart' option is enabled or not.

**Comment by huaiyukhaw** [comment]
Same happened to me. Have you found any solution?

**Comment by hunter-koppen** [comment]
@warrengay @huaiyukhaw I have updated the module, had to publish it as a new appstore compontent since I dont work at the same company as before. You can find the new one here:
https://marketplace.mendix.com/link/component/227661

The autostart should also be fixed now.

**Comment by huaiyukhaw** [comment]
Nice, thank you for updating this!
